# Generated by Django 3.2.10 on 2021-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfConverter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='file_name',
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
