# Generated by Django 3.2.10 on 2021-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfConverter', '0002_auto_20211217_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_file', models.FileField(default='', max_length=254, upload_to='Pdf_uploads/')),
            ],
        ),
    ]
